package com.jpayment.rest.util;

import java.util.HashMap;

public class CountryMap {
	private static HashMap<String, String> mapCountry;
	static {
		mapCountry.put("AU", "Australia");
		mapCountry.put("CN", "China");
		mapCountry.put("JP", "Japan");
		mapCountry.put("TH", "Thailand");
		mapCountry.put("IN", "India");
		mapCountry.put("MY", "Malaysia");
		mapCountry.put("KR", "Korea");
		mapCountry.put("HK", "Hong Kong");
		mapCountry.put("TW", "Taiwan");
		mapCountry.put("PH", "Philippines");
		mapCountry.put("VN", "Vietnam");
		mapCountry.put("FR", "France");
		mapCountry.put("EU", "Europe");
		mapCountry.put("DE", "Germany");
		mapCountry.put("SE", "Sweden");
		mapCountry.put("IT", "Italy");
		mapCountry.put("GR", "Greece");
		mapCountry.put("ES", "Spain");
		mapCountry.put("AT", "Austria");
		mapCountry.put("GB", "United Kingdom");
		mapCountry.put("NL", "Netherlands");
		mapCountry.put("BE", "Belgium");
		mapCountry.put("CH", "Switzerland");
		mapCountry.put("AE", "United Arab Emirates");
		mapCountry.put("IL", "Israel");
		mapCountry.put("UA", "Ukraine");
		mapCountry.put("RU", "Russian Federation");
		mapCountry.put("KZ", "Kazakhstan");
		mapCountry.put("PT", "Portugal");
		mapCountry.put("SA", "Saudi Arabia");
		mapCountry.put("DK", "Denmark");
		mapCountry.put("IR", "Iran");
		mapCountry.put("NO", "Norway");
		mapCountry.put("US", "United States");
		mapCountry.put("CA", "Canada");
		mapCountry.put("MX", "Mexico");
		mapCountry.put("BM", "Bermuda");
		mapCountry.put("SY", "Syrian Arab Republic");
		mapCountry.put("KW", "Kuwait");
		mapCountry.put("BH", "Bahrain");
		mapCountry.put("LB", "Lebanon");
		mapCountry.put("QA", "Qatar");
		mapCountry.put("OM", "Oman");
		mapCountry.put("JO", "Jordan");
		mapCountry.put("CZ", "Czech Republic");
		mapCountry.put("IQ", "Iraq");
		mapCountry.put("TR", "Turkey");
		mapCountry.put("RO", "Romania");
		mapCountry.put("HU", "Hungary");
		mapCountry.put("GE", "Georgia");
		mapCountry.put("SG", "Singapore");
		mapCountry.put("BG", "Bulgaria");
		mapCountry.put("MA", "Morocco");
		mapCountry.put("LV", "Latvia");
		mapCountry.put("AF", "Afghanistan");
		mapCountry.put("BZ", "Belize");
		mapCountry.put("EG", "Egypt");
		mapCountry.put("ZA", "South Africa");
		mapCountry.put("BR", "Brazil");
		mapCountry.put("AR", "Argentina");
		mapCountry.put("VG", "Virgin Islands");
		mapCountry.put("CY", "Cyprus");
		mapCountry.put("FI", "Finland");
		mapCountry.put("PL", "Poland");
		mapCountry.put("BD", "Bangladesh");
		mapCountry.put("IE", "Ireland");
		mapCountry.put("NG", "Nigeria");
		mapCountry.put("MC", "Monaco");
		mapCountry.put("EE", "Estonia");
		mapCountry.put("YE", "Yemen");
		mapCountry.put("BA", "Bosnia and Herzegovina");
		mapCountry.put("SZ", "Swaziland");
		mapCountry.put("LT", "Lithuania");
		mapCountry.put("NZ", "New Zealand");
		mapCountry.put("UG", "Uganda");
		mapCountry.put("AL", "Albania");
		mapCountry.put("HR", "Croatia");
		mapCountry.put("MT", "Malta");
		mapCountry.put("KE", "Kenya");
		mapCountry.put("DO", "Dominican Republic");
		mapCountry.put("PA", "Panama");
		mapCountry.put("PK", "Pakistan");
		mapCountry.put("PS", "Palestinian Territory");
		mapCountry.put("AZ", "Azerbaijan");
		mapCountry.put("BI", "Burundi");
		mapCountry.put("ZM", "Zambia");
		mapCountry.put("ZW", "Zimbabwe");
		mapCountry.put("CD", "Congo");
		mapCountry.put("AO", "Angola");
		mapCountry.put("A2", "Satellite Provider");
		mapCountry.put("LU", "Luxembourg");
		mapCountry.put("RS", "Serbia");
		mapCountry.put("IS", "Iceland");
		mapCountry.put("SI", "Slovenia");
		mapCountry.put("MD", "Moldova");
		mapCountry.put("MK", "Macedonia");
		mapCountry.put("CG", "Congo");
		mapCountry.put("LI", "Liechtenstein");
		mapCountry.put("JE", "Jersey");
		mapCountry.put("SN", "Senegal");
		mapCountry.put("PY", "Paraguay");
		mapCountry.put("KG", "Kyrgyzstan");
		mapCountry.put("RE", "Reunion");
		mapCountry.put("LY", "Libya");
		mapCountry.put("AM", "Armenia");
		mapCountry.put("BY", "Belarus");
		mapCountry.put("GI", "Gibraltar");
		mapCountry.put("BS", "Bahamas");
		mapCountry.put("GT", "Guatemala");
		mapCountry.put("CR", "Costa Rica");
		mapCountry.put("MU", "Mauritius");
		mapCountry.put("SK", "Slovakia");
		mapCountry.put("GP", "Guadeloupe");
		mapCountry.put("MQ", "Martinique");
		mapCountry.put("GY", "Guyana");
		mapCountry.put("LK", "Sri Lanka");
		mapCountry.put("UY", "Uruguay");
		mapCountry.put("SC", "Seychelles");
		mapCountry.put("AD", "Andorra");
		mapCountry.put("AG", "Antigua and Barbuda");
		mapCountry.put("AI", "Anguilla");
		mapCountry.put("AQ", "Antarctica");
		mapCountry.put("AS", "American Samoa");
		mapCountry.put("AW", "Aruba");
		mapCountry.put("AX", "Aland Islands");
		mapCountry.put("BB", "Barbados");
		mapCountry.put("BF", "Burkina Faso");
		mapCountry.put("BJ", "Benin");
		mapCountry.put("BL", "Saint Barthelemy");
		mapCountry.put("BN", "Brunei Darussalam");
		mapCountry.put("BO", "Bolivia");
		mapCountry.put("BQ", "Bonaire");
		mapCountry.put("BT", "Bhutan");
		mapCountry.put("BW", "Botswana");
		mapCountry.put("CC", "Cocos (Keeling) Islands");
		mapCountry.put("CF", "Central African Republic");
		mapCountry.put("CI", "Cote D'Ivoire");
		mapCountry.put("CK", "Cook Islands");
		mapCountry.put("CL", "Chile");
		mapCountry.put("CM", "Cameroon");
		mapCountry.put("CO", "Colombia");
		mapCountry.put("CU", "Cuba");
		mapCountry.put("CV", "Cape Verde");
		mapCountry.put("CW", "Curacao");
		mapCountry.put("CX", "Christmas Island");
		mapCountry.put("DJ", "Djibouti");
		mapCountry.put("DM", "Dominica");
		mapCountry.put("DZ", "Algeria");
		mapCountry.put("EC", "Ecuador");
		mapCountry.put("EH", "Western Sahara");
		mapCountry.put("ER", "Eritrea");
		mapCountry.put("ET", "Ethiopia");
		mapCountry.put("FJ", "Fiji");
		mapCountry.put("FK", "Falkland Islands (Malvinas)");
		mapCountry.put("FM", "Micronesia");
		mapCountry.put("FO", "Faroe Islands");
		mapCountry.put("GA", "Gabon");
		mapCountry.put("GD", "Grenada");
		mapCountry.put("GF", "French Guiana");
		mapCountry.put("GG", "Guernsey");
		mapCountry.put("GH", "Ghana");
		mapCountry.put("GL", "Greenland");
		mapCountry.put("GM", "Gambia");
		mapCountry.put("GN", "Guinea");
		mapCountry.put("GQ", "Equatorial Guinea");
		mapCountry.put("GS", "South Georgia and the South Sandwich Islands");
		mapCountry.put("GU", "Guam");
		mapCountry.put("GW", "Guinea-Bissau");
		mapCountry.put("HN", "Honduras");
		mapCountry.put("HT", "Haiti");
		mapCountry.put("ID", "Indonesia");
		mapCountry.put("IM", "Isle of Man");
		mapCountry.put("IO", "British Indian Ocean Territory");
		mapCountry.put("JM", "Jamaica");
		mapCountry.put("KI", "Kiribati");
		mapCountry.put("KM", "Comoros");
		mapCountry.put("KN", "Saint Kitts and Nevis");
		mapCountry.put("KP", "Korea");
		mapCountry.put("KY", "Cayman Islands");
		mapCountry.put("LA", "Lao People's Democratic Republic");
		mapCountry.put("LC", "Saint Lucia");
		mapCountry.put("LR", "Liberia");
		mapCountry.put("LS", "Lesotho");
		mapCountry.put("ME", "Montenegro");
		mapCountry.put("MF", "Saint Martin");
		mapCountry.put("MG", "Madagascar");
		mapCountry.put("MH", "Marshall Islands");
		mapCountry.put("ML", "Mali");
		mapCountry.put("MM", "Myanmar");
		mapCountry.put("MN", "Mongolia");
		mapCountry.put("MO", "Macau");
		mapCountry.put("MP", "Northern Mariana Islands");
		mapCountry.put("MR", "Mauritania");
		mapCountry.put("MS", "Montserrat");
		mapCountry.put("MV", "Maldives");
		mapCountry.put("MW", "Malawi");
		mapCountry.put("MZ", "Mozambique");
		mapCountry.put("NA", "Namibia");
		mapCountry.put("NC", "New Caledonia");
		mapCountry.put("NE", "Niger");
		mapCountry.put("NF", "Norfolk Island");
		mapCountry.put("NI", "Nicaragua");
		mapCountry.put("NP", "Nepal");
		mapCountry.put("NR", "Nauru");
		mapCountry.put("NU", "Niue");
		mapCountry.put("PE", "Peru");
		mapCountry.put("PF", "French Polynesia");
		mapCountry.put("PG", "Papua New Guinea");
		mapCountry.put("PM", "Saint Pierre and Miquelon");
		mapCountry.put("PN", "Pitcairn Islands");
		mapCountry.put("PR", "Puerto Rico");
		mapCountry.put("PW", "Palau");
		mapCountry.put("RW", "Rwanda");
		mapCountry.put("SB", "Solomon Islands");
		mapCountry.put("SD", "Sudan");
		mapCountry.put("SH", "Saint Helena");
		mapCountry.put("SJ", "Svalbard and Jan Mayen");
		mapCountry.put("SL", "Sierra Leone");
		mapCountry.put("SM", "San Marino");
		mapCountry.put("SO", "Somalia");
		mapCountry.put("SR", "Suriname");
		mapCountry.put("SS", "South Sudan");
		mapCountry.put("ST", "Sao Tome and Principe");
		mapCountry.put("SV", "El Salvador");
		mapCountry.put("SX", "Sint Maarten (Dutch part)");
		mapCountry.put("TC", "Turks and Caicos Islands");
		mapCountry.put("TD", "Chad");
		mapCountry.put("TF", "French Southern Territories");
		mapCountry.put("TG", "Togo");
		mapCountry.put("TJ", "Tajikistan");
		mapCountry.put("TK", "Tokelau");
		mapCountry.put("TL", "Timor-Leste");
		mapCountry.put("TM", "Turkmenistan");
		mapCountry.put("TN", "Tunisia");
		mapCountry.put("TO", "Tonga");
		mapCountry.put("TT", "Trinidad and Tobago");
		mapCountry.put("TV", "Tuvalu");
		mapCountry.put("TZ", "Tanzania");
		mapCountry.put("UM", "United States Minor Outlying Islands");
		mapCountry.put("UZ", "Uzbekistan");
		mapCountry.put("VA", "Holy See (Vatican City State)");
		mapCountry.put("VC", "Saint Vincent and the Grenadines");
		mapCountry.put("VE", "Venezuela");
		mapCountry.put("VI", "Virgin Islands");
		mapCountry.put("VU", "Vanuatu");
		mapCountry.put("WF", "Wallis and Futuna");
		mapCountry.put("WS", "Samoa");
		mapCountry.put("YT", "Mayotte");
		mapCountry.put("A1", "Anonymous Proxy");
		mapCountry.put("AP", "Asia/Pacific Region");
		mapCountry.put("KH", "Cambodia");
	}

	public static String getCountry(String code) {
		return mapCountry.get(code);
	}
}
